name: Qodo AI PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/review')) }}
    steps:
      - uses: qodo-ai/pr-agent@main
        with:
          openai_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          openai_api_model: claude-3-7-sonnet-20250219
          openai_base_url: ${{ secrets.ANTHROPIC_BASE_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_review: true
          auto_describe: true
          custom_config: |
            {
              "review": {
                "require_tests": true,
                "require_changelog": true,
                "extra_ignore_patterns": ["**/*.md", "docs/**/*"]
              }
            }
